apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: devops-cluster
  region: ap-south-1

nodeGroups:
  - name: devops-cluster-1
    instanceType: t2.medium
    desiredCapacity: 2
    volumeSize: 5
    ssh:
      allow: false
