    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: ingress-service
      annotations:
        kubernetes.io/ingress.class: 'nginx'
        # Bellow line allow regex after '/'
        nginx.ingress.kubernetes.io/use-regex: 'true'
        # Using bellow line manage remove first Prefix to url
        nginx.ingress.kubernetes.io/rewrite-target: /$1
    spec:
      rules:
        - http:
            paths:
              - path: /?(.*)
                pathType: Prefix
                backend:
                  service:
                    name: client-clusterip
                    port:
                      number: 3000
              - path: /api/?(.*)
                pathType: Prefix
                backend:
                  service:
                    name: server-clusterip
                    port:
                      number: 5000